### ISSUE TITLE
IOError: [Errorno 2]

### ISSUE THREAD

**Issue by olympiador** [Shando/WorldEngine_UI_Win64#1]
Tried to create a world and this error pops-up near the end of processing:

> Traceback (most recent call last):
>   File "worldengine\main.py", line 795, in spnWidthChanged
> AttributeError: 'MyApp' object has no attribute 'spnExportSubOffWidth'
> Traceback (most recent call last):
>   File "worldengine\main.py", line 1527, in onActionGenerate
>   File "worldengine\main.py", line 1814, in cli_main
>   File "worldengine\main.py", line 2027, in onActionMapsBiome
>   File "worldengine\draw.py", line 1077, in draw_biome_on_file
>   File "worldengine\image_io.py", line 186, in complete
> IOError: [Errno 2] No such file or directory: u'D:\\Downloads\\WorldEngine_UI_Wi
> n64-master\\WorldEngine_UI_Win64-master/Maps/seed_42158_biome.png'
> 

Here are th world details:
```
WorldEngine - a world generator (v. 0.19.0)
------------------------------------------------------------------------------------
 seed                 : 42158
 name                 : seed_42158.world
 width                : 2048
 height               : 1024
 number of plates     : 20
 world format         : png
 world data type      : uint8
 black and white maps : False
 fade borders         : True
 temperature ranges   : [0.126, 0.235, 0.406, 0.561, 0.634, 0.876]
 humidity ranges      : [0.059, 0.222, 0.493, 0.764, 0.927, 0.986, 0.998]
 gamma value          : 1.25
 gamma offset         : 0.2

starting ... 
NB: This could take a long time (10+ minutes) and the UI will become unresponsive.
    For example, on a Core i7-4700MQ @ 2.4GHz, Plates Simulation takes more than
    a minute, Ocean Initialisation about 4 minutes and the Watermap Simulation
    about 3 minutes. So, approximately 8 minutes for these three parts alone!
 
* world data saved in 'seed_42158.world'

Producing Output ...
```

**Comment by Shando** [comment]
Hey buddy, sorry to hear that :(

Can you try adding an empty 'Maps' folder and seeing if that fixes it??

When I uploaded to GitHub, it seems that it doesn't upload empty folders.

Let me know.

Thanks

Shando

PS: The error message you posted has also helped me track down another bug :)

**Comment by olympiador** [comment]
Hi forgot to answer - I did what you've suggested and it works fine now, thanks.
